c_stdlib_version:              # [osx and x86_64]
  - '10.12'                    # [osx and x86_64]
MACOS_DEPLOYEMENT_TARGET:      # [osx and x86_64]
  - '10.12'                    # [osx and x86_64]
